### 1. Get Orders By Id
GET http://localhost:5000/orders/408138d5-62c4-4d6d-b863-bdf802ed2794
Accept: application/json


### 2.  Create Orders
POST http://localhost:5000/orders
Content-Type: application/json

{
  "orderDate": "2020-05-25",
  "customerId": "ec6b79c2-56fd-43e9-869c-6f22b91b8710",
  "paymentMethod": "credit",
  "orderItems": [
    {
      "productId": "0F9F118B-8D41-4EE0-A294-5CBCFB6F61C1",
      "quantity": 10
    },
    {
      "productId": "1EAE3B54-8ED5-4B52-BD6A-F6F078D73ED7",
      "quantity": 8
    },
    {
      "productId": "3FC6B8D7-5820-4E65-9C0F-2B7D0D3E6A35",
      "quantity": 10
    }
  ]
}

### 3. Get Orders By Id using DAPR
GET http://localhost:5500/v1.0/invoke/orders/method/orders/408138d5-62c4-4d6d-b863-bdf802ed2794
Accept: application/json


### 4.  Create Orders via DAPR
POST http://localhost:5500/v1.0/invoke/orders/method/orders
Content-Type: application/json

{
  "orderDate": "2020-05-25",
  "customerId": "ec6b79c2-56fd-43e9-869c-6f22b91b8710",
  "paymentMethod": "credit",
  "orderItems": [
    {
      "productId": "0F9F118B-8D41-4EE0-A294-5CBCFB6F61C1",
      "quantity": 10
    },
    {
      "productId": "1EAE3B54-8ED5-4B52-BD6A-F6F078D73ED7",
      "quantity": 8
    },
    {
      "productId": "3FC6B8D7-5820-4E65-9C0F-2B7D0D3E6A35",
      "quantity": 10
    }
  ]
}


### 5. Get Orders By Id using DAPR ID
GET http://localhost:5500/orders/408138d5-62c4-4d6d-b863-bdf802ed2794
Accept: application/json
dapr-app-id: orders